#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom&

bspc monitor -d I II III IV V VI VII

bspc config border_width         4
bspc config window_gap          12
bspc config focused_border_color "#f7a600"
bspc config initial_polarity	first_child
bspc config automatic_scheme		spiral
bspc config split_ratio          0.53
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a URxvt state=pseudo_tiled
bspc rule -a mplayer2 state=floating
bspc rule -a St state=pseudo_tiled
bspc rule -a Surf state=tiled
bspc rule -a Typora state=tiled desktop=^2 follow=on
bspc rule -a feh state=tiled
bspc rule -a calibre:calibre-ebook-viewer state=tiled desktop=^3 follow=on
bspc rule -a Zathura state=fullscreen desktop=^3 follow=on

pkill polybar
polybar example &

~/.fehbg &
